<Project>
  <PropertyGroup>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageProjectUrl>https://www.monogame.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/bytinggames/MonoGame</RepositoryUrl>
    <Authors>MonoGame Team, Byting Games</Authors>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)Images\Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>

