<Project>
  <PropertyGroup>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageProjectUrl>https://www.monogame.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/bytinggames/MonoGame</RepositoryUrl>
    <Authors>MonoGame Team, Byting Games</Authors>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
	  <!-- to set the correct version when building within Visual Studio.
	  This must be the same as in build.cake:10-->
	  <Version>3.8.1.21-develop</Version>
	  <AssemblyVersion>3.8.1.21</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)Images\Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>

